const DEFAULT_PERMISSIONS = [
  { key: '*', description: 'Full access (all permissions).' },
  { key: 'app.access', description: 'Access to base application routes.' },
  { key: 'providers.manage_own', description: 'Create/update/delete own providers.' },
  { key: 'prompts.generate', description: 'Generate provider output from templates.' },
  { key: 'history.manage_own', description: 'Read/write own prompt history.' },
  { key: 'library.manage_own', description: 'Manage own prompt library entries.' },
  { key: 'library.view_public', description: 'View public library entries.' },
  { key: 'library.rate', description: 'Rate visible library entries.' },
  { key: 'settings.manage_own', description: 'Manage own user settings.' },
  { key: 'templates.read', description: 'Read visible templates and taxonomy.' },
  { key: 'templates.manage_own', description: 'Create and manage own personal templates.' },
  { key: 'templates.submit_review', description: 'Submit own templates for review.' },
  { key: 'templates.use_community', description: 'Use approved community templates.' },
  { key: 'templates.nodes.manage_own', description: 'Create/manage own taxonomy nodes.' },
  { key: 'templates.review', description: 'Review and approve/reject community templates.' },
  { key: 'templates.official_manage', description: 'Create/manage official templates.' },
  { key: 'templates.nodes.official_manage', description: 'Create/manage official taxonomy nodes.' },
  { key: 'templates.community_manage', description: 'Manage approved community templates.' },
  { key: 'tags.read', description: 'Read tags and tag catalog.' },
  { key: 'tags.manage_own', description: 'Manage own personal/community tags.' },
  { key: 'tags.moderate', description: 'Moderate official/community tags.' },
  { key: 'admin.access', description: 'Access admin interface.' },
  { key: 'rbac.manage', description: 'Manage roles, permissions and group-role bindings.' },
  { key: 'pricing.manage', description: 'Manage provider model pricing catalog.' },
  { key: 'providers.system_keys.manage', description: 'Manage system-wide provider keys and assignments.' },
  { key: 'budgets.manage', description: 'Manage global budget policies (user/group/key).' },
  { key: 'budgets.manage_own', description: 'Manage personal budget policies for own usage.' },
];

const DEFAULT_ROLES = [
  {
    key: 'teachers',
    name: 'Teachers',
    description: 'Default application users.',
    system: true,
    permissions: [
      'app.access',
      'providers.manage_own',
      'prompts.generate',
      'history.manage_own',
      'library.manage_own',
      'library.view_public',
      'library.rate',
      'settings.manage_own',
      'templates.read',
      'templates.manage_own',
      'templates.submit_review',
      'templates.use_community',
      'templates.nodes.manage_own',
      'tags.read',
      'tags.manage_own',
      'budgets.manage_own',
    ],
  },
  {
    key: 'prompt_creator_template_reviewers',
    name: 'Prompt Creator Template Reviewers',
    description: 'Review and moderation for community templates.',
    system: true,
    permissions: [
      'app.access',
      'templates.read',
      'templates.review',
      'templates.use_community',
      'tags.read',
      'tags.moderate',
      'admin.access',
    ],
  },
  {
    key: 'prompt_creator_template_curators',
    name: 'Prompt Creator Template Curators',
    description: 'Official template and taxonomy management.',
    system: true,
    permissions: [
      'app.access',
      'templates.read',
      'templates.review',
      'templates.official_manage',
      'templates.nodes.official_manage',
      'templates.community_manage',
      'templates.use_community',
      'tags.read',
      'tags.moderate',
      'admin.access',
      'pricing.manage',
      'providers.system_keys.manage',
      'budgets.manage',
    ],
  },
  {
    key: 'prompt_creator_platform_admins',
    name: 'Prompt Creator Platform Admins',
    description: 'Full platform and RBAC administration.',
    system: true,
    permissions: ['*'],
  },
];

const DEFAULT_GROUP_ROLE_BINDINGS = [
  { groupName: 'teachers', roleKey: 'teachers' },
  { groupName: 'prompt_creator_template_reviewers', roleKey: 'prompt_creator_template_reviewers' },
  { groupName: 'prompt_creator_template_curators', roleKey: 'prompt_creator_template_curators' },
  { groupName: 'prompt_creator_platform_admins', roleKey: 'prompt_creator_platform_admins' },
];

module.exports = {
  DEFAULT_PERMISSIONS,
  DEFAULT_ROLES,
  DEFAULT_GROUP_ROLE_BINDINGS,
};
